sudo: false
language: java

script:
  - gradle build
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey=ecse429-tutorial-05 -Dsonar.projectName=ecse429-tutorial-05

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

